name: "Release"

on:
  push:
    # Run on release branches scenarios supported by the
    # `@ethima/semantic-release-configuration`
    branches:
      - "main"
      - "release-**"

jobs:
  release:
    name: "Release"
    runs-on: self-hosted
    steps:
      - name: "Run Dyad release process"
        uses: "JuliaComputing/dyad-release-process@c15f78807a62bd16c1bd70eedf2a951806dc7a09" # v2.0.0
        with:
          encoded-juliahub-token: "${{ secrets.JULIAHUB_TOKEN_ENCODED }}"
          release-manager-app-id: "${{ secrets.JULIASIM_RELEASE_MANAGER_APP_ID }}"
          release-manager-private-key: "${{ secrets.JULIASIM_RELEASE_MANAGER_PRIVATE_KEY }}"
          julia-pkg-registry: "JSMLComponents"
          ssh-key: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"
